### PR TITLE
bugfix: Nx.BinaryBackend.Matrix.ts/8 returns corrupted matrix when b has more columns than rows

### LINKED ISSUE #1427: Nx.LinAlg.solve/2 with Nx.BinaryBackend returns tensor with wrong state
`Nx.LinAlg.solve(a, b)` with `Nx.BinaryBackend` returns tensor with wrong state when `b` has more columns than rows.

For example,

```elixir
a = Nx.tensor([
  [1, 1],
  [1, 2]
], type: :f64)

b = Nx.tensor([
  [2, 2, 2],
  [3, 3, 3]
], type: :f64)

x = Nx.LinAlg.solve(a, b)

Nx.shape(x)  # returns {2, 3} as expected

byte_size(x.data.state)  # expected: 48, actual: 32
```

I was trying to spot the issue, but it seems the issue is inside the function `Nx.BinaryBackend.Matrix.ts/8`, which I don't know what it's doing.

`EXLA.Backend` has no such issue.

### PR DESCRIPTION
**Pull request by Aetherus**
closes #1427

### CODE REVIEW

File: nx/lib/nx/binary_backend/matrix.ex [hunk 1]
```diff
@@ -7,151 +7,90 @@ defmodule Nx.BinaryBackend.Matrix do
...
       case b_shape do
         {_rows, _cols} ->
-          b_data |> binary_to_matrix(b_type, b_shape) |> ts_handle_opts(opts, :b)
+          b_data |> binary_to_matrix(b_type, b_shape)
 
         {_rows} ->
-          b_data |> binary_to_vector(b_type) |> ts_handle_opts(opts, :b)
+          b_data |> binary_to_vector(b_type)
+      end
+      |> then(& transpose_b? && transpose_matrix(&1) || &1)
```
Comment (polvalente) [inline nx/lib/nx/binary_backend/matrix.ex]:
```suggestion
      |> then(&if(transpose_b?, do: transpose_matrix(&1), else: &1))
```

Stylistically, I find inline ifs instead of using && and || for a ternary selection to be a more clear option because it doesn't require thinking about operator precedence

File: nx/lib/nx/binary_backend/matrix.ex [hunk 2]
```diff
@@ -7,151 +7,90 @@ defmodule Nx.BinaryBackend.Matrix do
...
+    transpose_x? = transpose_b?
+    reverse_x? = reverse_b?
 
     a_matrix =
       a_data
       |> binary_to_matrix(a_type, a_shape)
-      |> ts_transform_a(transform_a)
-      |> ts_handle_opts(opts, :a)
+      |> then(&((transpose_a? && transpose_matrix(&1)) || &1))
+      |> then(&((reverse_a? && reverse_matrix(&1)) || &1))
```
Comment (polvalente) [inline nx/lib/nx/binary_backend/matrix.ex:64]: I believe my comment was sent to limbo due to the force push. Please acknowledge it in the main PR tab, as it applies to both these lines

Comment (Aetherus) [reply nx/lib/nx/binary_backend/matrix.ex]: Thank you for your code style suggestion. I changed it to inline if-else.

**Review by polvalente — APPROVED** [review]
Thanks!
