### PR TITLE
Fix Nx.is_tensor for non-finite atoms

### LINKED ISSUE #1219: `Nx.is_tensor/1` for :nan and :infinity
`Nx.is_tensor/1` returns `true` for numbers but not for atoms `:nan`, `:infinity` and `:neg_infinity`.

```
iex(26)> Nx.is_tensor(42.0)
true
iex(27)> Nx.is_tensor(:nan)
false
```

### PR DESCRIPTION
**Pull request by petrkozorezov**
fixes #1219

### CODE REVIEW

File: nx/lib/nx.ex [hunk 1]
```diff
@@ -423,13 +423,13 @@ defmodule Nx do
   @doc """
   Checks whether the value is a valid numerical value.
 
-  Returns true if the value is a `number`, a `Complex` number or an `Nx.Tensor`.
+  Returns true if the value is a `number`, a non-finite atom (like :infinity), a `Complex` number or an `Nx.Tensor`.
```
Comment (josevalim) [inline nx/lib/nx.ex:426]:
```suggestion
  Returns true if the value is a `number`, a non-finite atom (like `:infinity`),
  a `Complex` number or an `Nx.Tensor`.
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
