### PR TITLE
fix(torchx): support full_matrices

### LINKED ISSUE #1083: [Torchx] Nx.LinAlg.svd doesn't support full_matrices? correctly
Torchx has a bug that ends up returning a full `vt` matrix instead of the partial one.

```elixir
iex(7)> {u, s, vt} = Nx.LinAlg.svd(Nx.iota({4, 10}), full_matrices?: false)
{#Nx.Tensor<
   f32[4][4]
   Torchx.Backend(cpu)
   [
     [-0.10590074211359024, -0.8299309015274048, 0.29091382026672363, -0.46407845616340637],
     [-0.3256263732910156, -0.4404173195362091, -0.041982050985097885, 0.835606038570404],
     [-0.545352041721344, -0.05090371146798134, -0.7887787818908691, -0.2789764404296875],
     [-0.765077531337738, 0.3386090397834778, 0.539846658706665, -0.09255106002092361]
   ]
 >,
 #Nx.Tensor<
   f32[4]
   Torchx.Backend(cpu)
   [143.0361785888672, 8.9804048538208, 3.7290064938133582e-6, 9.29894270029763e-7]
 >,
 #Nx.Tensor<
   f32[4][10]
   Torchx.Backend(cpu)
   [
     [-0.25948411226272583, -0.27166256308555603, -0.283841073513031, -0.29601946473121643, -0.30819791555404663, -0.32037633657455444, -0.33255478739738464, -0.34473323822021484, -0.35691165924072266, -0.3690900504589081],
     [0.5273731350898743, 0.41795244812965393, 0.3085317611694336, 0.19911101460456848, 0.08969025313854218, -0.01973048411309719, -0.12915122509002686, -0.23857198655605316, -0.3479927182197571, -0.4574134051799774],
     [-0.3728494644165039, -0.509186327457428, 0.4891280233860016, 0.3390675187110901, 0.26160579919815063, 0.16822831332683563, 0.10728275030851364, -0.17667311429977417, 0.021390801295638084, -0.3279942274093628],
     [0.664271354675293, -0.6556040048599243, -0.2817078232765198, 0.06307585537433624, 0.07567134499549866, -0.006990334484726191, 0.05294286832213402, 0.15999570488929749, 0.03067491203546524, -0.10232988744974136]
   ]
 >}
iex(8)> u
#Nx.Tensor<
  f32[4][4]
  Torchx.Backend(cpu)
  [
    [-0.10590074211359024, -0.8299309015274048, 0.29091382026672363, -0.46407845616340637],
    [-0.3256263732910156, -0.4404173195362091, -0.041982050985097885, 0.835606038570404],
    [-0.545352041721344, -0.05090371146798134, -0.7887787818908691, -0.2789764404296875],
    [-0.765077531337738, 0.3386090397834778, 0.539846658706665, -0.09255106002092361]
  ]
>
iex(9)> s
#Nx.Tensor<
  f32[4]
  Torchx.Backend(cpu)
  [143.0361785888672, 8.9804048538208, 3.7290064938133582e-6, 9.29894270029763e-7]
>
iex(10)> vt
#Nx.Tensor<
  f32[4][10]
  Torchx.Backend(cpu)
  [
    [-0.25948411226272583, -0.27166256308555603, -0.283841073513031, -0.29601946473121643, -0.30819791555404663, -0.32037633657455444, -0.33255478739738464, -0.34473323822021484, -0.35691165924072266, -0.3690900504589081],
    [0.5273731350898743, 0.41795244812965393, 0.3085317611694336, 0.19911101460456848, 0.08969025313854218, -0.01973048411309719, -0.12915122509002686, -0.23857198655605316, -0.3479927182197571, -0.4574134051799774],
    [-0.3728494644165039, -0.509186327457428, 0.4891280233860016, 0.3390675187110901, 0.26160579919815063, 0.16822831332683563, 0.10728275030851364, -0.17667311429977417, 0.021390801295638084, -0.3279942274093628],
    [0.664271354675293, -0.6556040048599243, -0.2817078232765198, 0.06307585537433624, 0.07567134499549866, -0.006990334484726191, 0.05294286832213402, 0.15999570488929749, 0.03067491203546524, -0.10232988744974136]
  ]
>
iex(11)> vt |> Torchx.from_nx() |> Torchx.to_nx()
#Nx.Tensor<
  f32[10][10]
  Torchx.Backend(cpu)
  [
    [-0.25948411226272583, -0.27166256308555603, -0.283841073513031, -0.29601946473121643, -0.30819791555404663, -0.32037633657455444, -0.33255478739738464, -0.34473323822021484, -0.35691165924072266, -0.3690900504589081],
    [0.5273731350898743, 0.41795244812965393, 0.3085317611694336, 0.19911101460456848, 0.08969025313854218, -0.01973048411309719, -0.12915122509002686, -0.23857198655605316, -0.3479927182197571, -0.4574134051799774],
    [-0.3728494644165039, -0.509186327457428, 0.4891280233860016, 0.3390675187110901, 0.26160579919815063, 0.16822831332683563, 0.10728275030851364, -0.17667311429977417, 0.021390801295638084, -0.3279942274093628],
    [0.664271354675293, -0.6556040048599243, -0.2817078232765198, 0.06307585537433624, 0.07567134499549866, -0.006990334484726191, 0.05294286832213402, 0.15999570488929749, 0.03067491203546524, -0.10232988744974136],
    [-0.08731772005558014, 0.07356468588113785, -0.2365855574607849, -0.30667388439178467, 0.8996121287345886, -0.09370545297861099, -0.08927993476390839, -0.03438107296824455, -0.09315240383148193, -0.032080721110105515],
    ...
  ]
>
```

I'll open an issue for us to track it

_Originally posted by @polvalente in https://github.com/elixir-nx/nx/issues/1081#issuecomment-1405413383_

### PR DESCRIPTION
**Pull request by polvalente**
closes #1083

### CODE REVIEW

File: torchx/test/torchx_test.exs [hunk 1]
```diff
@@ -299,4 +299,25 @@ defmodule TorchxTest do
...
+      assert {%{shape: {4, 4}} = u, %{shape: {4}} = s, %{shape: {4, 10}} = vt} = Nx.LinAlg.svd(t, full_matrices?: false)
+      assert_all_close(t, u |> Nx.multiply(s) |> Nx.dot(vt))
+
+      assert {%{shape: {4, 4}} = u, %{shape: {4}} = s, %{shape: {10, 10}} = vt} = Nx.LinAlg.svd(t, full_matrices?: true)
+
+      s_diag = Nx.eye({4, 10}) |> Nx.put_diagonal(s)
+      a = u |> Nx.dot(s_diag) |> Nx.dot(vt)
+      assert_all_close(t, a)
+
+
```
Comment (josevalim) [inline torchx/test/torchx_test.exs:315]:
```suggestion

```

**Review by josevalim — APPROVED** [review]
