### PR TITLE
fix: make exla build resilient to stale upgrades

### LINKED ISSUE #1546: "module EXLA.NIF is not available"  What does this mean?
image

Hi.   I am not a genius like Jose Valim.   I do not have 10 years in Docker experience.  I am just a statistician and cannot spend days of my life learning how to compile things.   

Can someone give a clear and concise, plain english description on what is happening here?  It has destroyed my app and I can no longer run it after upgrading.

### PR DESCRIPTION
**Pull request by polvalente**
fixes #1546

### CODE REVIEW

File: exla/mix.exs [hunk 1]
```diff
@@ -133,7 +134,23 @@ defmodule EXLA.MixProject do
...
+    clean_libexla_cache? = parsed[:clean_libexla_cache] == true
+    force? = parsed[:force] == true
+
+    if force? do
+      Mix.shell().info("Removing cached .o files in cache/#{@version}/objs")
+      File.rm_rf!("cache/#{@version}/objs")
+    end
+
+    if clean_libexla_cache? or force? do
+      Mix.shell().info("Removing cached libexla.so files in cache/libexla.so")
```
Comment (jonatanklosko) [inline exla/mix.exs:150]:
```suggestion
      Mix.shell().info("Removing cached libexla.so file in cache/libexla.so")
```

File: exla/lib/exla/nif.ex [hunk 2]
```diff
@@ -4,7 +4,20 @@ defmodule EXLA.NIF do
...
+    case :erlang.load_nif(path, 0) do
+      :ok ->
+        :ok
+
+      {:error, {reason, text}} ->
+        raise """
+        Failed to load NIF library.
+        Follow the steps in the :exla README Troubleshooting section for more information.
+
+        #{reason}
```
Comment (jonatanklosko) [inline exla/lib/exla/nif.ex:17]:
```suggestion
        #{inspect(reason)}
```

**Comment by jonatanklosko** [comment]
Looks good to me!

File: exla/README.md [hunk 3]
```diff
@@ -48,6 +48,22 @@ EXLA relies on the [XLA](https://github.com/elixir-nx/xla) package to provide th
...
 For cross-compilation, you need to [set your `XLA_TARGET_PLATFORM` variable](https://github.com/elixir-nx/xla#xla_target_platform) to the correct target platform value (i.e. `aarch64-linux-gnu` for the Raspberry Pi 4).
 
+## Troubleshooting
+
+EXLA uses NIFs (C-interface code called from Elixir) for part of its functionality.
+If for any reason these fail to compile or load, troubleshooting can be tricky.
+
+We recommend following the steps below:
+
+  1. If the error appeared after upgrading EXLA, ensure that you have the proper dependency versions given by [XLA](https://github.com/elixir-nx/xla). Afterwards, compile with `mix compile --clean-libexla-cache --force` to clean up all cached files.
```
Comment (josevalim) [inline exla/README.md:58]: `mix compile` is not going to work when compiled as a dependency. We would need to introduce a separate mix compiler or a separate task.

Comment (josevalim) [reply exla/README.md:58]: It won’t work in the sense that it won’t invoke the code you added in the mix.exs file. `mix compile` is only about the local project. Maybe an env var with `mix deps.compile exla` will work.

File: exla/mix.exs [hunk 4]
```diff
@@ -133,7 +134,23 @@ defmodule EXLA.MixProject do
     {:ok, []}
   end
 
-  defp cached_make(_) do
+  defp cached_make(args) do
+    {parsed, _args, _invalid} =
+      OptionParser.parse(args, strict: [clean_libexla_cache: :boolean, force: :boolean])
```
Comment (josevalim) [inline exla/mix.exs:139]: Suggestion to make this a single env var called EXLA_FORCE_REBUILD, as explained above.

Comment (polvalente) [reply exla/mix.exs:139]: Env var is probably the simpler alternative :)

File: exla/README.md (hunk 3 above)
Comment (jonatanklosko) [reply exla/README.md:58]: @josevalim it may works as `mix deps.clean exla --build --clean-libexla-cache`?

Comment (jonatanklosko) [reply exla/README.md:58]: err `mix deps.compile exla --force --clean-libexla-cache`

Comment (jonatanklosko) [reply exla/README.md:58]: But yeah, env var sounds better either way.

Comment (josevalim) [reply exla/README.md:58]: I am not sure if we pass options forward in all of these cases. Although we should probably make `mix deps.clean` for dependencies extensible, so we actually invoke `clean` in the relevant dep.

File: exla/Makefile [hunk 5]
```diff
@@ -9,7 +9,7 @@ XLA_INCLUDE_PATH = $(XLA_EXTENSION_DIR)/include
 
 # Cache configuration
 EXLA_CACHE_SO = cache/libexla.so
```
Comment (josevalim) [inline exla/Makefile:11]: Shouldn't we version this one as well? Just in case?

```suggestion
EXLA_CACHE_SO = cache/$(EXLA_VERSION)/libexla.so
```

File: exla/mix.exs [hunk 6]
```diff
@@ -150,14 +167,21 @@ defmodule EXLA.MixProject do
     cached_so = Path.join([xla_cache_dir(), "exla", cache_key, "libexla.so"])
     cached? = File.exists?(cached_so)
```
Comment (josevalim) [inline exla/mix.exs:168]: I think you can mostly remove the changes to this function and instead simply write this:

```suggestion
    cached? = System.get_env("XLA_FORCE_REBUILD") == nil and File.exists?(cached_so)
```

Comment (josevalim) [reply exla/mix.exs:168]: This will be enough to force a rebuild and write the new build to cache.

File: exla/Makefile (hunk 5 above)
Comment (polvalente) [reply exla/Makefile:11]: Shouldn't hurt :)
I'd tried this during development but it had failed. Seems to be working locally now.

File: exla/mix.exs (hunk 6 above)
Comment (polvalente) [reply exla/mix.exs:167]: @josevalim I changed to using env vars, but kept 2 separate ones because there are many instances in which I wanted to leverage the `.o` caching while getting rid of the libexla.so file and cache, as well as instances where I wanted to clean-slate everything.

Comment (josevalim) [reply exla/mix.exs:167]: My problem with the above is that, if something is not working, I need to set two env vars to clear everything. So why not a single env var with different values?

  * `XLA_FORCE_REBUILD=1` - remove all
  * `XLA_FORCE_REBUILD=partial` - keep .o

Also, is there any situation where you don't want to cache files to be rewritten? I don't see a reason to skip that as part of these options?

Finally note that we use `XLA` env vars for pretty much everything, since we have `XLA_CACHE_DIR`, etc.

Comment (polvalente) [reply exla/mix.exs:167]: I'm ok with having special values for the env var and having a single one.

I disagree with using `XLA` as the prefix, though, as this doesn't have anything to do with `:xla`. `XLA_CACHE_DIR` being used in EXLA is just an artifact of "let's use the same subdir for both XLA and EXLA". The origin of the variable is in `:xla`.

> Also, is there any situation where you don't want to cache files to be rewritten? I don't see a reason to skip that as part of these options?

As for this part, I don't think we are skipping the rewrite.

Comment (polvalente) [reply exla/mix.exs]: I refactored the `cached?` check so that there's less confusion about whether rewrites will happen.
`cached?` will now be set to false regardless of the file existing if force rebuild is set.

File: exla/test/exla/device_memory_sharing_test.exs [hunk 7]
```diff
@@ -27,14 +27,13 @@ defmodule EXLA.DeviceMemorySharingTest do
   end
 
   @tag :cuda_required
-  test "ipc handles don't crash the runtime when :local mode is selected" do
-    assert {:error, ~c"Invalid pointer size for selected mode."} ==
+  test "invalid ipc handles don't crash the runtime" do
```
Comment (polvalente) [inline exla/test/exla/device_memory_sharing_test.exs:30]: This test was breaking locally (I guess I hadn't run it on my desktop since the update :stuck_out_tongue:)

File: exla/mix.exs [hunk 8]
```diff
@@ -133,7 +134,38 @@ defmodule EXLA.MixProject do
...
+          false
+
+        "partial" ->
+          :partial
+
+        "true" ->
+          true
+
+        "1" ->
+          true
```
Comment (josevalim) [inline exla/mix.exs:153]:
```suggestion
         :none

        "0" ->
          :none

        "partial" ->
          :partial

        "true" ->
          :full

        "1" ->
          :full
```

This should force all the code below to be explicit :)
