### PR TITLE
Fix names bug on reshape with same shape

### LINKED ISSUE #250: Nx.reshape with the existing shape won't update the names.
```
>
iex(17)> t = Nx.tensor([1, 2, 3, 4])
#Nx.Tensor<
  s64[4]
  [1, 2, 3, 4]
>
iex(19)> t |> Nx.reshape({1, 4}) |> Nx.reshape({2, 2}, names: [:x, :y])
#Nx.Tensor<
  s64[x: 2][y: 2]
  [
    [1, 2],
    [3, 4]
  ]
>
iex(20)> t |> Nx.reshape({2, 2}) |> Nx.reshape({2, 2}, names: [:x, :y])
#Nx.Tensor<
  s64[2][2]
  [
    [1, 2],
    [3, 4]
  ]
>
```
The expected iex(20) result should be with names `:x` and `:y`

### PR DESCRIPTION
**Pull request by seanmor5**
Resolves #250

### CODE REVIEW

File: nx/lib/nx.ex [hunk 1]
```diff
@@ -1262,6 +1262,16 @@ defmodule Nx do
         ]
       >
 
+      iex> t = Nx.tensor([[1, 2], [3, 4]])
```
Comment (josevalim) [inline nx/lib/nx.ex:1265]: Since this doesn’t have much purpose as an example, perhaps an actual test?

**Review by josevalim — APPROVED** [review]
Looks good, just one comment!

also please double check if we don’t have the same bug on broadcast
