### PR TITLE
fix: vectorized Nx.take

### LINKED ISSUE #1192: Batch over vectorized indices in `Nx.take/2`
Currently `take` uses the first row of indices instead of vmapping:

```elixir
t = Nx.tensor([[1, 2], [3, 4]]) |> Nx.vectorize(:x)
idx = Nx.tensor([[1, 0], [0, 1]]) |> Nx.vectorize(:x)
Nx.take(t, idx)
```

```
#Nx.Tensor<
  vectorized[x: 2]
  s64[2]
  [
    [2, 1],
    [4, 3]
  ]
>
```

We have [`batched_take` in Bumblebee](https://github.com/elixir-nx/bumblebee/blob/6c4d88544d7d93a073bfd6f3b2dd9743ca93d245/lib/bumblebee/utils/nx.ex#L249-L278), but I don't think this technique generalizes to also support `:axis` without additional transpose (it relies on batch axes being adjacent to `:axis`, so those can be flattened out).

### PR DESCRIPTION
**Pull request by polvalente**
closes #1192

This basically replicates the algorithm for take-over-gather used in Torchx, so that we extend the still-vectorized indices to be passed onto the vectorized gather implementation.

Implementing directly over take would imply lots of really weird slicing and wouldn't yield much memory footprint improvement over what we have now.

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

File: nx/lib/nx.ex [hunk 1]
```diff
@@ -13293,83 +13293,97 @@ defmodule Nx do
...
+      indices = if rank(indices) == 0, do: new_axis(indices, 0), else: indices
 
-        indices =
-          devec_indices
-          |> slice(starts, lengths)
-          |> squeeze(axes: Enum.reverse(indices_squeeze_axes_rev))
+      indices_shape =
+        axes_range
+        |> Enum.flat_map(fn
+          ^axis -> Tuple.to_list(indices.shape)
```
Comment (jonatanklosko) [inline nx/lib/nx.ex:13329]: Perhaps we could use `Tuple.product(indices.shape)` and remove `axis_offset`, since it's all flattened out anyway?

**Review by jonatanklosko — APPROVED** [review]

File: nx/lib/nx.ex [hunk 2]
```diff
@@ -13293,83 +13293,89 @@ defmodule Nx do
...
+        |> Enum.with_index(fn
+          _x, ^axis ->
+            1
 
-        {shape, names, indices}
-      end
+          x, _ ->
+            x
+        end)
+        |> List.flatten()
```
Comment (jonatanklosko) [inline nx/lib/nx.ex:13344]:
```suggestion
```
