### PR TITLE
runtime_call now only accepts named captures w/ opts restored

### LINKED ISSUE #1684: runtime_call should only accept named captures with the opts argument restored
Currently, the code below is accepted by runtime_call with the inline anonymous function, but fails due to the `defp` not being defn-enabled.

```elixir
defn foo(arg, opts) do
  ...

  ... = Nx.runtime_call(arg, arg, fn t -> 
    do_something(t, opts)
  end

  ...
end

defp do_something(t, opts) do 
  ...
end
```

We should instead accept `Nx.runtime_call(out, arg, opts, &named_capture/2)`, restoring the `opts` argument for static/compile-time values (this can also be used to capture anything that would be a closure). It is a bit more bureaucratic in that we have to define the function, but removes any confusion on the boundary.

### PR DESCRIPTION
**Pull request by Chapaman**
closes #1684

### **Summary of Changes**

---

### **1. `Nx.Defn.Compiler` (`nx/lib/nx/defn/compiler.ex`)**

- Added `validate_runtime_call!/3` and `validate_runtime_call_capture!/4` to enforce **named captures only** in `Nx.runtime_call`
- Validation runs **during normalization** when processing `Nx.runtime_call` calls
- Accepts **only** named captures with **arity 2**:
  - Local: `&fun/2` (atom or var-style name in AST)
  - Remote: `&Mod.fun/2` (unaliased or aliased module)
- Rejects:
  - Anonymous functions (`fn x, y -> ... end`)
  - Anonymous captures (e.g. `&(&1 + &2)`, `&(&1 / &2)`)
  - Wrong arity (e.g. `&fun/1`) with message "got arity N"
  - Operator captures (e.g. `&Kernel.+/2`) via `@forbidden_capture_names`
- Remote capture AST: `{:/, _, [{{:., _, [mod, name]}, _, []}, 2]}`

---

### **2. `Nx` (`nx/lib/nx.ex`)**

- `runtime_call(output, tensor_or_container, opts \\ [], fun)` when `is_function(fun, 2)`
- `opts` defaults to `[]`
- Callback is **always arity 2**: `fun.(tensor_or_container, opts)`
- Updated doctest to use named capture with `RuntimeCallExample` module

---

### **3. `Nx.Defn.Expr` (`nx/lib/nx/defn/expr.ex`)**

- `runtime_call(out, tensor_or_container, opts, fun)` when `is_function(fun, 2)`
- Stores `[tensor_expr, fun, out_template, opts]` in the expression node

---

### **4. `Nx.Defn.Evaluator` (`nx/lib/nx/defn/evaluator.ex`)**

- `eval_apply(:runtime_call, [expr, fun, out_template, opts], ...)` calls `fun.(tensor_value, opts)`

---

### **5. `Nx.Defn.Tree` (`nx/lib/nx/defn/tree.ex`)**

- `apply_args` expects `[tensor_expr, callback, out_template, opts]`

---

### **6. `EXLA.CallbackServer` (`exla/lib/exla/callback_server.ex`)**

- `register(pid, id, fun, out_template, arg_template, opts)` with `is_function(fun, 2)`
- `run_callback` calls `fun.(tensor_args, opts)`

---

### **7. `EXLA.Defn` (`exla/lib/exla/defn.ex`)**

- `cached_recur_operator` for `:runtime_call` uses `[tensor_expr, fun, out_template, opts]`

---

### **8. Tests**

- **Evaluator** (`nx/test/nx/defn/runtime_call_evaluator_test.exs`):
  - All callbacks use `&fun/2` with signature `(tensor, opts)`
  - Added `RemoteCallback` module for remote capture tests
  - Added tests for fully-qualified unaliased (`&Mod.fun/2`) and aliased (`&Alias.fun/2`) modules
  - Added failure-case tests: anonymous function, anonymous capture, wrong arity
- **EXLA** (`exla/test/exla/defn/runtime_call_test.exs`): callbacks use `&fun/2` with `(tensor, opts)`

### CODE REVIEW

File: nx/lib/nx/defn/compiler.ex [hunk 1]
```diff
@@ -724,6 +729,65 @@ defmodule Nx.Defn.Compiler do
...
+      when is_atom(name) or
+             (is_tuple(name) and tuple_size(name) == 3 and is_atom(elem(name, 0))) ->
+        :ok
+
+      {{:., _, [mod, name]}, _, [2]}
+      when (is_atom(mod) or (is_tuple(mod) and elem(mod, 0) == :__aliases__)) and
+             (is_atom(name) or
+                (is_tuple(name) and tuple_size(name) == 3 and is_atom(elem(name, 0)))) ->
+        :ok
+
```
Comment (polvalente) [inline nx/lib/nx/defn/compiler.ex]: Let's split these into 4 separate cases, I think it'll be a bit more readable

File: nx/lib/nx/defn/compiler.ex [hunk 2]
```diff
@@ -724,6 +729,65 @@ defmodule Nx.Defn.Compiler do
...
+      [_out, _arg, _opts, fun] ->
+        validate_runtime_call_capture!(fun, 2, meta, state)
+
+      _ ->
+        compile_error!(
+          meta,
+          state,
+          "Nx.runtime_call/3 expects (out, arg, &fun/2) and Nx.runtime_call/4 expects (out, arg, opts, &fun/2), got #{length(args)} arguments"
+        )
```
Comment (polvalente) [inline nx/lib/nx/defn/compiler.ex]: This should probably be an UndefinedFunctionError:

```elixir 
iex(1)> defmodule M do
...(1)> def f(x), do: x
...(1)> end
{:module, M,
 <<70, 79, 82, 49, 0, 0, 5, 92, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 161,
   0, 0, 0, 17, 8, 69, 108, 105, 120, 105, 114, 46, 77, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 10, 97, 116, 116, 114, ...>>, {:f, 1}}
iex(2)> M.f(1, 2)
** (UndefinedFunctionError) function M.f/2 is undefined or private. Did you mean:

      * f/1

    M.f(1, 2)
    iex:2: (file)
```


```suggestion
        raise UndefinedFunctionError, "function Nx.runtime_call/#{length(args)} is undefined. Did you mean runtime_call/3 or runtime_call/4?"
```

File: nx/test/nx/defn/runtime_call_evaluator_test.exs [hunk 3]
```diff
@@ -58,31 +80,57 @@ defmodule Nx.Defn.RuntimeCallEvaluatorTest do
...
+      end
+    end
+
+    test "rejects anonymous capture (& &1 + &2)" do
+      assert_raise CompileError, ~r/requires a named capture/, fn ->
+        defmodule BadAnonCapture do
+          import Nx.Defn
+
+          defn bad(x) do
+            Nx.runtime_call(x, x, &(&1 + &2))
```
Comment (polvalente) [inline nx/test/nx/defn/runtime_call_evaluator_test.exs]:
```suggestion
            Nx.runtime_call(x, x, &(&1 / &2))
```

This catches a confusion case where the ast could be confused with &function/arity, but `:&` are special names that we should detect as bad ones

File: nx/test/nx/defn/runtime_call_evaluator_test.exs [hunk 4]
```diff
@@ -58,31 +80,57 @@ defmodule Nx.Defn.RuntimeCallEvaluatorTest do
...
+          end
+        end
+      end
+    end
+
+    test "rejects wrong arity (&fun/1)" do
+      assert_raise CompileError, ~r/requires a named capture.*got:.*&callback\/1/, fn ->
```
[the remark this answers is not in the document]
Comment (polvalente) [reply nx/test/nx/defn/runtime_call_evaluator_test.exs]: Also, do we have a test showing that both unaliased and aliased modules work for fully-qualified &Mod.fun/2?

File: nx/lib/nx/defn/compiler.ex [hunk 5]
```diff
@@ -724,6 +729,95 @@ defmodule Nx.Defn.Compiler do
...
+  # Reject special names that indicate anonymous captures confused with &function/arity:
+  #   - {:&, _, [n]} - the &1, &2 placeholders (e.g. & &1/2 parses as &(&1)/2 with name=&1)
+  #   - :/ - division operator (e.g. &(&1 / &2) expands to &Kernel.//2)
+  defp validate_runtime_call_capture!({:&, _, [arg]}, _expected_arity, meta, state) do
+    case arg do
+      {:/, _, [name, 2]} when is_atom(name) and name != :/ ->
+        :ok
+
+      {:/, _, [name, 2]}
+      when is_tuple(name) and tuple_size(name) == 3 and is_atom(elem(name, 0)) and
```
Comment (polvalente) [inline nx/lib/nx/defn/compiler.ex]:
```suggestion
      {:/, _, [{name, _, _}, 2]} when is_atom(name) and name != :&
```

File: nx/lib/nx/defn/compiler.ex [hunk 6]
```diff
@@ -724,6 +729,95 @@ defmodule Nx.Defn.Compiler do
...
+             (is_atom(name) or
+               (is_tuple(name) and tuple_size(name) == 3 and is_atom(elem(name, 0)) and
+                  elem(name, 0) != :&)) ->
+        :ok
+
+      {:/, _, [{{:., _, [mod, name]}, _, []}, 2]}
+      when is_tuple(mod) and elem(mod, 0) == :__aliases__ and name != :/ and
+             (is_atom(name) or
+               (is_tuple(name) and tuple_size(name) == 3 and is_atom(elem(name, 0)) and
+                  elem(name, 0) != :&)) ->
```
Comment (polvalente) [inline nx/lib/nx/defn/compiler.ex]:
```suggestion
      {:/, _, [{{:., _, [{:__aliases, _, [mod]}, name]}, _, []}, 2]} when is_atom(mod) and is_atom(name) ->
```

File: nx/lib/nx/defn/compiler.ex [hunk 7]
```diff
@@ -638,6 +638,11 @@ defmodule Nx.Defn.Compiler do
     end
 
     {args, state} = normalize_list(args, state)
+
+    if name == :runtime_call do
+      validate_runtime_call!(args, meta, state)
```
Comment (josevalim) [inline nx/lib/nx/defn/compiler.ex]: You want to do this before you call `normalize_list`, as `normalize_list` is the one that will crash for "weird reasons".

File: nx/lib/nx/defn/compiler.ex [hunk 8]
```diff
@@ -724,6 +729,95 @@ defmodule Nx.Defn.Compiler do
...
+    )
+  end
+
+  # Require :& with only argument being {:/, _, [name, 2]} (local) or {:/, _, [{{:., _, [mod, name]}, _, []}, 2]} (remote).
+  # Arity must be the literal 2 to reject dynamic captures like &fun/arity where arity is a variable.
+  # Name must be atom (static) or var-style {atom, _, _} (compile-time variable), not a dynamic expression.
+  # Reject special names that indicate anonymous captures confused with &function/arity:
+  #   - {:&, _, [n]} - the &1, &2 placeholders (e.g. & &1/2 parses as &(&1)/2 with name=&1)
+  #   - :/ - division operator (e.g. &(&1 / &2) expands to &Kernel.//2)
+  defp validate_runtime_call_capture!({:&, _, [arg]}, _expected_arity, meta, state) do
```
Comment (josevalim) [inline nx/lib/nx/defn/compiler.ex]: You don't need to pass `expected_arity` as argument, since it is always 2.

File: nx/lib/nx/defn/compiler.ex (hunk 7 above)
Comment (polvalente) [reply nx/lib/nx/defn/compiler.ex]: Not sure how this got reordered without killing the comment, but I'll mark this one as resolved.
