### PR TITLE
fix(torchx): avoid returning bool type in underlying tensors

### LINKED ISSUE #895: Torchx not compatible with Axon
Hello,

I was trying Torchx as a backend for Nx but when I try to run the `mnist.ex` example in Axon using Torchx I get the following in the train phase.

```
** (RuntimeError) Torchx: "argmax_cpu" not implemented for 'Bool' in NIF.argmax/3
    (torchx 0.3.0) lib/torchx.ex:409: Torchx.unwrap!/1
    (torchx 0.3.0) lib/torchx.ex:412: Torchx.unwrap_tensor!/2
    (torchx 0.3.0) lib/torchx/backend.ex:703: Torchx.Backend.argminmax/4
    (nx 0.3.0) lib/nx/defn/evaluator.ex:185: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.3.0) lib/nx/defn/evaluator.ex:82: Nx.Defn.Evaluator.eval/3
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.3.0) lib/nx/defn/evaluator.ex:163: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.3.0) lib/nx/defn/evaluator.ex:82: Nx.Defn.Evaluator.eval/3
```

### PR DESCRIPTION
**Pull request by polvalente**
closes #895

This is an edge case which I wasn't able to reproduce through normal Nx APIs.
Some torch functions return a bool-typed tensor instead of byte-typed for u8.
This leads to some unexpected behavior which was mostly hidden under an upcast we had specifically for u8 -> s16.

This PR converts all bool underlying tensors to byte tensors when returning to Nx-land

### CODE REVIEW

File: torchx/test/torchx_test.exs [hunk 1]
```diff
@@ -91,4 +91,35 @@ defmodule TorchxTest do
...
+
+  describe "bool type" do
+    test "adds correctly" do
+      t_tx =
+        {2, 3}
+        |> Nx.iota(type: {:u, 8})
+        |> Torchx.from_nx()
+        |> Torchx.to_type(:bool)
+
+      # t = Torchx.Backend.to_nx(t_tx, %Nx.Tensor{names: [nil, nil], shape: {2, 3}, type: {:u, 8}})
```
Comment (polvalente) [inline torchx/test/torchx_test.exs:103]:
```suggestion
```

**Review by josevalim — APPROVED** [review]

**Review by josevalim — APPROVED** [review]
