### PR TITLE
fix: broadcast vectors for grad calculation

### LINKED ISSUE #1533: Nx.Defn.Grad returns sum of gradient over vectorized axis?
Thanks for making Nx!

I tried to use `value_and_grad` on a function that takes two inputs: a vectorized tensor and a non-vectorized tensor.

``` elixir
defmodule Foo do
  import Nx.Defn
  defn f(x, y) do
    x + y
  end

  defn f_and_grad(x, y) do
    value_and_grad(y, fn y -> Foo.f(x, y) end)
  end
end

x = ~VEC[0 1] |> vectorize(:bar)
Foo.f_and_grad(x, 1)
```

This evaluates to:

```
{#Nx.Tensor<
   vectorized[bar: 2]
   s64
   EXLA.Backend<host:0, 0.731981912.321781778.128426>
   [1, 2]
 >,
 #Nx.Tensor<
   f32
   EXLA.Backend<host:0, 0.731981912.321781778.128427>
   2.0
 >}
```

The value is correct and maintains the vectorized axis of the vectorized input to `x`, but the gradient surprises me. I would have expected a vectorized tensor rank-1 dimension-2 vector with the same `:foo` axis and which is everywhere `1`; it looks like instead Nx is summing up the two gradients.

Is this behavior expected? If so, is there any way to make Nx return a vectorized gradient?

Thanks!

### PR DESCRIPTION
**Pull request by polvalente**
closes #1533

### CODE REVIEW

File: nx/lib/nx/defn/grad.ex [hunk 1]
```diff
@@ -5,12 +5,19 @@ defmodule Nx.Defn.Grad do
...
+      Composite.traverse(to_grad, {%{}, broadcasted_nodes}, fn _to_grad,
+                                                               {ids, [broadcasted_node | nodes]} ->
         to_grad =
-          Expr.metadata(to_grad, %{__MODULE__ => :to_grad})
+          Expr.metadata(broadcasted_node, %{__MODULE__ => :to_grad})
 
-        {to_grad, Map.put(ids, to_grad.data.id, :stop)}
+        ids = Map.put(ids, to_grad.data.id, :stop)
+        {to_grad, {ids, nodes}}
       end)
```
Comment (polvalente) [inline nx/lib/nx/defn/grad.ex:21]: This isn't actually the proper fix. This solves the issue only when there is no closure for a vectorized tensor.
fn y -> Nx.add(x, y) end fails if y is unvectorized but x is vectorized

File: nx/lib/nx/defn/grad.ex [hunk 2]
```diff
@@ -19,36 +18,32 @@ defmodule Nx.Defn.Grad do
...
     {expr, graded}
   end
 
   defp constant(float, shape) do
-    shape = Nx.shape(shape)
-    names = List.duplicate(nil, tuple_size(shape))
-    Expr.constant(%T{shape: shape, type: {:f, 32}, names: names}, float, [])
+    case shape do
+      %T{vectorized_axes: [_ | _]} = t ->
+        Expr.tensor(Nx.fill(t, float, type: :f32))
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:40]: We should probably get rid of the names here too.

I also wonder if should move the check for vectorized_axes to `constant`. Today if someone passes vectorized_axes, Expr.constant is broken. So maybe we should create a tensor if a vectorized axes is given to tensor?

File: nx/lib/nx/defn/grad.ex [hunk 3]
```diff
@@ -338,6 +333,8 @@ defmodule Nx.Defn.Grad do
   @verify_grad Application.compile_env(:nx, :verify_grad, false)
 
   defp update_grads(op, args, ans, g, _to_grad_ids, grads) do
+    args = revectorize_args(args, ans)
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:336]: I would prefer to not revectorized everything on every operation. Is there any chance we could do in `broadcast` only?

Comment (polvalente) [reply nx/lib/nx/defn/grad.ex:336]: `[unbroadcast(x, Nx.multiply(g, y), ans), unbroadcast(y, Nx.multiply(g, x), ans)]`

Lines like this one make it so that `g` is vectorized and `y` is unvectorized but has axes with the same name, so things break there.

File: nx/lib/nx/defn/grad.ex (hunk 2 above)
Comment (polvalente) [reply nx/lib/nx/defn/grad.ex]: Done!

File: nx/lib/nx/defn/expr.ex [hunk 4]
```diff
@@ -1394,6 +1394,11 @@ defmodule Nx.Defn.Expr do
 
   ## Constant helpers and related optimizations
 
+  defp constant(%{vectorized_axes: [_ | _]} = out, number) do
+    out = %{out | names: Enum.map(out.names, fn _ -> nil end)}
```
Comment (josevalim) [inline nx/lib/nx/defn/expr.ex:1398]: I don't think this part should be done here, we should preserve the names. Sorry for the confusion.

File: nx/lib/nx/defn/grad.ex [hunk 5]
```diff
@@ -1343,9 +1334,77 @@ defmodule Nx.Defn.Grad do
 
   ## General helpers
 
-  defp unbroadcast(%{shape: shape} = x, res, %{shape: shape}), do: {x, res}
+  defp revectorize_args(args, ans) do
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:1337]: Let's only apply this if args has more than one element and there are vectorized axes.


Also please test `x * sin(y)` where y is vectorized.

**Review by josevalim — APPROVED** [review]

File: nx/lib/nx.ex [hunk 6]
```diff
@@ -4906,12 +4906,19 @@ defmodule Nx do
 
   def devectorize(%T{shape: shape, names: names, vectorized_axes: vectorized_axes} = tensor, opts)
       when vectorized_axes != [] do
-    opts = keyword!(opts, keep_names: true)
+    opts = keyword!(opts, keep_names: true, drop_inner_names: false)
```
Comment (josevalim) [inline nx/lib/nx.ex:4909]: Revert.

File: nx/lib/nx/defn/expr.ex [hunk 7]
```diff
@@ -94,13 +94,13 @@ defmodule Nx.Defn.Expr do
...
       %{data: %{context: context}} = res ->
-        expr(res, context, :metadata, [Nx.devectorize(expr), metadata])
+        expr(res, context, :metadata, [expr, metadata])
 
       t when is_tuple(t) ->
         context = elem(t, 0).data.context
 
         tuple(
-          expr(tuple_out(tuple_size(t)), context, :metadata, [Nx.devectorize(expr), metadata]),
+          expr(tuple_out(tuple_size(t)), context, :metadata, [expr, metadata]),
```
Comment (josevalim) [inline nx/lib/nx/defn/expr.ex:103]: Revert. devectorize with keep_names.

File: nx/lib/nx/defn/expr.ex [hunk 8]
```diff
@@ -1661,11 +1665,11 @@ defmodule Nx.Defn.Expr do
...
-  defp to_type_shape(%{type: type, shape: shape}) do
-    brackets =
-      shape
-      |> Tuple.to_list()
-      |> Enum.map(&[?[, Integer.to_string(&1), ?]])
+  defp to_type_shape(%{vectorized_axes: vectorized_axes, type: type, shape: shape}) do
+    axes =
+      Keyword.values(vectorized_axes) ++ Tuple.to_list(shape)
+
+    brackets = Enum.map(axes, &[?[, Integer.to_string(&1), ?]])
```
Comment (josevalim) [inline nx/lib/nx/defn/expr.ex:1672]: Should we revert? 🤔

File: nx/lib/nx/defn/grad.ex [hunk 9]
```diff
@@ -93,47 +83,93 @@ defmodule Nx.Defn.Grad do
...
     case nodes do
-      %{^id => _} -> {parents, nodes}
-      %{} -> parents_args(op, t, id, {parents, Map.put(nodes, id, t)})
+      %{^id => _} ->
+        {parents, nodes}
+
+      %{} ->
+        parent_vectorized_axes = compute_arg_vectorized_axes(t, vectorized_axes)
+
+        nodes = Map.put(nodes, id, {Nx.devectorize(t, keep_names: true), parent_vectorized_axes})
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:101]: We should not have anything vectorized here.

File: nx/lib/nx/defn/grad.ex [hunk 10]
```diff
@@ -93,47 +83,93 @@ defmodule Nx.Defn.Grad do
...
     reduce_args(op, t, acc, fn arg, {parents, nodes} ->
       if arg.data.op in @constants do
         {parents, nodes}
       else
+        arg_vectorized_axes = compute_arg_vectorized_axes(t, parent_vectorized_axes)
         parents = Map.update(parents, arg.data.id, [parent_id], &[parent_id | &1])
-        recur_parents_tree(arg, {parents, nodes})
+
+        recur_parents_tree(
+          Nx.devectorize(arg, keep_names: true),
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:169]: We should not need this either.

File: nx/lib/nx/defn/grad.ex [hunk 11]
```diff
@@ -93,47 +83,93 @@ defmodule Nx.Defn.Grad do
...
-  defp recur_parents_tree(%T{data: %Expr{id: id, op: op}} = t, {parents, nodes}) do
+  defp recur_parents_tree(%T{data: %Expr{id: id, op: op}} = t, {parents, nodes}, vectorized_axes) do
     case nodes do
-      %{^id => _} -> {parents, nodes}
-      %{} -> parents_args(op, t, id, {parents, Map.put(nodes, id, t)})
+      %{^id => _} ->
+        {parents, nodes}
+
+      %{} ->
+        parent_vectorized_axes = compute_arg_vectorized_axes(t, vectorized_axes)
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:99]: This may not be necessary.

File: nx/lib/nx/defn/grad.ex [hunk 12]
```diff
@@ -212,6 +265,34 @@ defmodule Nx.Defn.Grad do
...
+      end)
+
+    vectorized_axes ++ Enum.reverse(reversed_inner_axes)
+  end
+
+  defp revectorize_node(node, vectorized_axes) do
+    vectorized_axes = compute_arg_vectorized_axes(node, vectorized_axes)
+
+    node
+    |> Nx.devectorize(keep_names: false)
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:292]: They should all be devectorized.

File: nx/lib/nx/defn/grad.ex [hunk 13]
```diff
@@ -1343,9 +1424,34 @@ defmodule Nx.Defn.Grad do
 
   ## General helpers
 
-  defp unbroadcast(%{shape: shape} = x, res, %{shape: shape}), do: {x, res}
+  defp unbroadcast(x, res, ans) do
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:1427]: Revert these changes.

File: nx/lib/nx/defn/grad.ex (hunk 11 above)
Comment (polvalente) [reply nx/lib/nx/defn/grad.ex]: I've changed the `compute_arg_vectorized_axes` function into a function that returns only the names (it's less assertive, but a tad cheaper), and that allows us to not need this remapping here.

It was needed for cases where `t` has [x: 1] and vectorized_axes has [x: 2], for instance -- implicit broadcast situations.

File: nx/lib/nx/defn/grad.ex [hunk 14]
```diff
@@ -213,6 +265,31 @@ defmodule Nx.Defn.Grad do
...
+    reversed_inner_axes =
+      Enum.reduce(names, [], fn name, acc ->
+        if name in parent_names do
+          [name | acc]
+        else
+          acc
+        end
+      end)
+
+    Keyword.keys(vectorized_axes) ++ Enum.reverse(reversed_inner_axes)
```
Comment (josevalim) [inline nx/lib/nx/defn/grad.ex:284]: This is a Enum.filter, no? 

```suggestion
    Keyword.keys(vectorized_axes) ++ Enum.filter(names, & &1 in parent_names)
```

**Review by josevalim — APPROVED** [review]
Beautiful!!!!! We can merge this and add the new ops later!

File: nx/lib/nx/defn/grad.ex (hunk 14 above)
Comment (polvalente) [reply nx/lib/nx/defn/grad.ex:284]: Yup. The loop had to iterate over multiple data structures before
