### PR TITLE
fix: Nx.Random.shuffle repeating a single value in certain cases on GPU

### LINKED ISSUE #1551: `Nx.Random.shuffle/3` fails for large tensors on `cuda` backend
When running the following code on an EXLA backend with a CUDA GPU, through the `livebook:0.14.5-cuda12` image:
```elixir
key = Nx.Random.key(1)
input = Nx.iota({1_000_000})
{output, _new_key} = Nx.Random.shuffle(key, input)
output
```
the result looks like this:
```elixir
#Nx.Tensor<
  s32[1000000]
  EXLA.Backend<cuda:0, 0.477854050.2664562754.2456>
  [163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, 163918, ...]
>
```
The bug also occurs for smaller tensors, but with a lesser frequency. The deciding factor is the size of the axis used for the shuffle, the other dimensions of the tensor do not seem to be relevant. It seems to start happening with an axis size around `100,000`, and is guaranteed after `1,000,000`.

Moreover, about half the time the execution never completes and the Livebook runtime has to be restarted.

This has been observed on two different machines, one with an RTX4090 graphics card and one with a GTX1070ti. The bug did not occur during testing on the CPU on the same machines.

### PR DESCRIPTION
**Pull request by polvalente**
fixes #1551

In short, what was happening is that we were not testing a specific edge case that resulted in an invalid-shaped tensor for the `sort_keys` sub-input in `sort_key_val`, that in turn yielded an invalid shuffle when the input is 1D.

### CODE REVIEW

File: nx/lib/nx/random.ex [hunk 1]
```diff
@@ -821,16 +827,25 @@ defmodule Nx.Random do
...
 
-  defnp sort_key_val(tensor, sort_keys, opts \\ []) do
+  deftransformp sort_key_val(tensor, sort_keys, opts \\ []) do
     idx = Nx.argsort(sort_keys, axis: opts[:axis])
-    Nx.take_along_axis(tensor, idx, axis: opts[:axis])
+
+    if opts[:independent] do
+      # We need to use take_along_axis in the independent case because
+      # the sort_keys tensor has the same shape as the input tensor.
+      Nx.take_along_axis(tensor, idx, axis: opts[:axis])
```
Comment (jonatanklosko) [inline nx/lib/nx/random.ex:843]: I think `take_along_axis` with 1D tensors is supposed to work just fine, the issue must be something else.

**Comment by jonatanklosko** [comment]
I'm still trying to narrow it down, but the issue must be somewhere in the combination of `random_bits` and `take_along_axis`. For example, if we make this change:

```diff
-sort_keys = random_bits(keys[1], shape: tensor.shape)
+sort_keys = randint_split(keys[1], 0, uint32max, shape: tensor.shape)
```

It seems to work just fine.

**Comment by jonatanklosko** [comment]
@polvalente actually, this also fixes it:

```diff
-sort_keys = random_bits(keys[1], shape: tensor.shape)
+sort_keys = random_bits(keys[1], shape: tensor.shape) |> Nx.as_type(:s32)
```

File: nx/lib/nx/random.ex (hunk 1 above)
Comment (polvalente) [reply nx/lib/nx/random.ex:843]: I wonder if this is actually a bug in EXLA's take_along_axis somehow.

The generated indices from argsort are returning with sensible values, but somehow these aren't being applied properly by take_along_axis

File: exla/lib/exla/mlir/value.ex [hunk 2]
```diff
@@ -66,19 +66,16 @@ defmodule EXLA.MLIR.Value do
...
         Nx.Type.complex?(lhs_type) or Nx.Type.complex?(rhs_type) ->
-          attr_comparison_type(:float)
+          [compare_type: attr_comparison_type(:float)]
 
         Nx.Type.float?(lhs_type) or Nx.Type.float?(rhs_type) ->
-          attr_comparison_type(:float)
+          [compare_type: attr_comparison_type(:float)]
 
         true ->
-          attr_comparison_type(:notype)
```
Comment (jonatanklosko) [inline exla/lib/exla/mlir/value.ex:75]: Let's also remove it here:

https://github.com/elixir-nx/nx/blob/08dc89336c5b15c42c2132b44f5aa28f93fd13ee/exla/lib/exla/mlir/value.ex#L1072

**Review by jonatanklosko — APPROVED** [review]

File: exla/test/exla/random_test.exs [hunk 3]
```diff
@@ -39,4 +39,23 @@ defmodule EXLA.NxRandomTest do
...
+
+  @tag :cuda_required
+  test "regression on single-dimensional and multi-dimensional Random.shuffle" do
+    # these are put in the process dictionary, so it's thread-safe to do this
+    Nx.default_backend({EXLA.Backend, client: :cuda})
+    Nx.Defn.default_options(compiler: EXLA, client: :cuda)
+    key = Nx.Random.key(127)
+
+    t1 = Nx.iota({2, 100})
+    t2 = Nx.iota({100})
```
Comment (jonatanklosko) [inline exla/test/exla/random_test.exs:51]: Does the test fail with the previous version? (the tensor is small)

Comment (polvalente) [reply exla/test/exla/random_test.exs:51]: Nah. I'm gonna remove this, specially now that we found the actual culprit

**Review by jonatanklosko — APPROVED** [review]
:shipit:
