### PR TITLE
fix: Nx.LinAlg.invert numerical stability

### LINKED ISSUE #1241: [Nx] Apply matrix normalization for Nx.LinAlg.invert in the default implementation
Basically the title, so we get better numerical stability. Related to #1240

### PR DESCRIPTION
**Pull request by polvalente**
closes #1241

### CODE REVIEW

File: nx/lib/nx/lin_alg.ex [hunk 1]
```diff
@@ -799,14 +805,24 @@ defmodule Nx.LinAlg do
...
       >
 
+  If a singular matrix is passed, the result will silently fail.
+
+      iex> Nx.LinAlg.invert(Nx.tensor([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1]]))
+      #Nx.Tensor<
+        f32[4][4]
+        [
+          [NaN, NaN, NaN, NaN],
+          [NaN, NaN, NaN, NaN],
```
Comment (josevalim) [inline nx/lib/nx/lin_alg.ex:815]:
```
          [NaN, NaN, NaN, NaN],           BATMAN!
```

**Review by josevalim — APPROVED** [review]
