### PR TITLE
Respect fortran order in loading from numpy

### LINKED ISSUE #1039: from_numpy giving incorrect results
Not sure the exact cause yet, but I have this array:

```
array([[ 0.15898602, -0.14751871, -0.18391664,  0.13925107, -0.19182335,
         0.03773712,  0.17069662, -0.17029768, -0.18824592,  0.13695134,
        -0.0753549 , -0.00577545, -0.03515474, -0.02577678,  0.18162225,
         0.2137578 , -0.19520882, -0.09311639, -0.2108432 ,  0.00161085],
       [-0.1187088 , -0.1731981 , -0.16642793,  0.18612117,  0.045352  ,
         0.1177659 , -0.09333479, -0.02148514,  0.1556263 , -0.08028746,
        -0.09144349, -0.05509386,  0.16841356, -0.06987406,  0.09861793,
         0.11010581,  0.0667009 ,  0.09077805, -0.0596639 ,  0.0017091 ],
       [-0.03219606, -0.07031839, -0.11429771, -0.16092066,  0.19732685,
        -0.00103716,  0.21620189, -0.21589942,  0.03671964, -0.17308183,
        -0.09312644, -0.2171458 ,  0.05608512,  0.03592835,  0.01390697,
        -0.05771295, -0.21723758, -0.19962342,  0.05347496, -0.10556599],
       [ 0.12669432, -0.02980715,  0.02983023,  0.19546925, -0.12550938,
        -0.0153924 ,  0.2038581 , -0.20470457, -0.09506934, -0.03007824,
         0.06496954, -0.08576493, -0.20165627, -0.16861582, -0.08791037,
        -0.04790556,  0.1285941 , -0.20482051,  0.00206   , -0.21462415],
       [ 0.04730716,  0.21222451,  0.10779023,  0.20589039, -0.02203535,
        -0.12569313,  0.10904101, -0.14247127,  0.08264487,  0.12674667,
         0.15316385,  0.01967368,  0.09470402, -0.0656772 ,  0.19611509,
         0.06393792,  0.21946594, -0.21053584,  0.19989006, -0.04469151],
       [-0.07596523, -0.14161068,  0.01480765,  0.08400764,  0.03030988,
        -0.15066837, -0.09977996,  0.0796623 , -0.20458043, -0.1965078 ,
        -0.02719526, -0.1989479 ,  0.04087139,  0.17728734, -0.21555106,
         0.1811458 , -0.12392628, -0.18785565,  0.12145197, -0.02176881],
       [-0.08549056,  0.00592062,  0.08458199,  0.057523  ,  0.02966582,
         0.20581345, -0.00946312, -0.08633734,  0.00973528,  0.04134555,
         0.04971737, -0.17759797, -0.02282711, -0.09943379,  0.14504936,
         0.10319209, -0.11977349, -0.06955637, -0.14821942,  0.14799684],
       [-0.02282629,  0.02099926, -0.04967429, -0.11664021, -0.2221491 ,
         0.04264297,  0.00268874,  0.20488644, -0.01145115, -0.06577919,
        -0.21485043, -0.06294256, -0.14831758,  0.05567347, -0.20209846,
        -0.1926295 , -0.06256495,  0.08774934, -0.13949832, -0.16998768],
       [-0.19936447,  0.11009899, -0.14709969, -0.13554615,  0.12769409,
         0.15576538, -0.18944336, -0.09824506, -0.10116565,  0.05778468,
        -0.01942226,  0.19301316, -0.17041953, -0.20138328,  0.05617724,
         0.13705906, -0.14781319,  0.19975401, -0.16839074,  0.03532049],
       [-0.004138  , -0.19286466, -0.16890995,  0.02979065, -0.14289734,
        -0.04425419, -0.01167229, -0.03652889,  0.15650246, -0.09530301,
         0.18106319, -0.20353258,  0.17010513, -0.06604836,  0.16501732,
        -0.18288599,  0.00965736,  0.11302712,  0.19277771, -0.14499612]],
      dtype=float32)
```

And I save it to a file (posted in EEF wg). I get incorrect results when decoding from numpy in Nx:

```
iex> Nx.from_numpy("test_lstm_cell_wii.npy")

#Nx.Tensor<
  f32[10][20]
  [
    [0.15898601710796356, -0.11870879679918289, -0.032196059823036194, 0.12669432163238525, 0.04730716347694397, -0.07596522569656372, -0.08549056202173233, -0.022826286032795906, -0.19936446845531464, -0.0041379984468221664, -0.14751870930194855, -0.17319810390472412, -0.07031838595867157, -0.02980714663863182, 0.21222451329231262, -0.14161068201065063, 0.005920619238168001, 0.020999256521463394, 0.11009898781776428, -0.19286465644836426],
    [-0.18391664326190948, -0.16642792522907257, -0.11429771035909653, 0.02983023039996624, 0.10779023170471191, 0.014807651750743389, 0.08458198606967926, -0.049674294888973236, -0.14709968864917755, -0.168909952044487, 0.13925106823444366, 0.1861211657524109, -0.1609206646680832, 0.19546924531459808, 0.20589038729667664, 0.0840076357126236, 0.05752299726009369, -0.11664021015167236, -0.13554614782333374, 0.029790647327899933],
    [-0.191823348402977, 0.04535199701786041, 0.19732685387134552, -0.1255093812942505, -0.022035349160432816, 0.030309880152344704, 0.029665816575288773, -0.2221491038799286, 0.12769408524036407, -0.1428973376750946, ...],
    ...
  ]
>
```

### PR DESCRIPTION
**Pull request by seanmor5**
Resolves #1039

### CODE REVIEW

File: nx/lib/nx.ex [hunk 1]
```diff
@@ -11581,6 +11581,14 @@ defmodule Nx do
     end
   end
 
+  defp reshape_with_order(tensor, shape, false), do: Nx.reshape(tensor, shape)
+
+  defp reshape_with_order(tensor, shape, true) do
+    shape = shape |> Tuple.to_list() |> Enum.reverse() |> List.to_tuple()
+
+    Nx.reshape(tensor, shape) |> Nx.transpose()
```
Comment (polvalente) [inline nx/lib/nx.ex:11589]: Can't we transpose the shape itself instead?

Comment (polvalente) [reply nx/lib/nx.ex:11589]: I'm a bit confused, though, because the docs for Nx.transpose say:

```
If no axes are given, the default behavior is to reverse the order of the
original tensor's axes.
```

Comment (polvalente) [reply nx/lib/nx.ex:11589]:
```elixir
iex(4)> shape = {2, 3, 4}
{2, 3, 4}
iex(5)> Nx.iota(shape |> Tuple.to_list() |> Enum.reverse() |> List.to_tuple()) |> Nx.transpose()
#Nx.Tensor<
  s64[2][3][4]
  [
    [
      [0, 6, 12, 18],
      [2, 8, 14, 20],
      [4, 10, 16, 22]
    ],
    [
      [1, 7, 13, 19],
      [3, 9, 15, 21],
      [5, 11, 17, 23]
    ]
  ]
>
```

Comment (polvalente) [reply nx/lib/nx.ex:11589]: Resolving the conversation due to self-rubberducking :)

Comment (polvalente) [reply nx/lib/nx.ex:11589]: Basically, Fortran order means column-major instead of row-major

**Review by polvalente — APPROVED** [review]
