### PR TITLE
Fix: Nx.LinAlg.determinant

### LINKED ISSUE #681: Default implementation for Nx.LinAlg.determinant has wrong sign
There's a bug related to the sign of the determinant. The 4x4 example has the wrong sign, but the 5x5 example is correct.

### PR DESCRIPTION
**Pull request by floatn**
closes #681 
It didn't calculate `parity` value properly.

### CODE REVIEW

File: nx/lib/nx/lin_alg.ex [hunk 1]
```diff
@@ -1199,12 +1199,18 @@ defmodule Nx.LinAlg do
...
 
-    iota = Nx.iota({n})
+    parity =
+      transform(transitions, fn transitions ->
+        {m} = Nx.shape(transitions)
 
-    parity = Nx.sum(Nx.dot(p, iota) != iota)
+        for i <- 0..(m - 1), reduce: 0 do
+          parity ->
+            Nx.add(parity, Nx.sum(Nx.greater(transitions[i], transitions[i..-1//1])))
```
Comment (polvalente) [inline nx/lib/nx/lin_alg.ex:1211]: Looks good! I'll try to find a non-transform implementation on this

**Review by polvalente — COMMENTED** [review]
Thanks! I had opened an issue on this earlier this week :)

File: nx/lib/nx/lin_alg.ex (hunk 1 above)
Comment (floatn) [reply nx/lib/nx/lin_alg.ex:1211]: > I had opened an issue on this earlier this week :)
I've started it on your report. Couldn't figure out how to handle it without transform, unfortunately.

Comment (polvalente) [reply nx/lib/nx/lin_alg.ex:1211]: I can't properly make a code suggestion here, but this is what I got:
```elixir
   transitions = Nx.dot(p, Nx.iota({n}))

    lower_tri_mask = {n, n} |> Nx.iota(axis: 0) |> Nx.greater(Nx.iota({n, n}, axis: 1))

    tiled_transitions = Nx.tile(transitions, [n, 1])

    tiled_transitions_with_mask = Nx.select(lower_tri_mask, n, tiled_transitions)

    parity =
      tiled_transitions
      |> Nx.transpose()
      |> Nx.greater(tiled_transitions_with_mask)
      |> Nx.sum()
```

Comment (polvalente) [reply nx/lib/nx/lin_alg.ex:1211]: This will use a bit more memory, but should be faster

Comment (polvalente) [reply nx/lib/nx/lin_alg.ex:1211]: This is the overall idea:

```elixir
iex(29)> Nx.tile(Nx.reshape(transitions, {4, 1}), [1, 4]) |> Nx.greater(tiled)
#Nx.Tensor<
  u8[4][4]
  [
    [0, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0]
  ]
>
iex(30)> for i<-0..3, do: Nx.greater(transitions[i], transitions[i..-1//1])                                                   [              
  #Nx.Tensor<
    u8[4]
    [0, 0, 0, 0]
  >,
  #Nx.Tensor<
    u8[3]
    [0, 1, 1]
  >,
  #Nx.Tensor<
    u8[2]
    [0, 1]
  >,
  #Nx.Tensor<
    u8[1]
    [0]
  >
]
```

Second result is what your code generates, first result is the last step before Nx.sum() in my snippet above

Comment (polvalente) [reply nx/lib/nx/lin_alg.ex:1211]: Multiply and select should be roughly the same speed. I had chosen select to ensure greater would fail by inserting a value greater than all others. If this works, it works!

File: nx/lib/nx/lin_alg.ex [hunk 2]
```diff
@@ -1193,18 +1193,22 @@ defmodule Nx.LinAlg do
...
-
     is_zero = Nx.any(diag == 0)
+    transitions = Nx.dot(p, Nx.iota({n}))
 
-    iota = Nx.iota({n})
+    upper_tri_mask = Nx.iota(nxn, axis: 0) |> Nx.less(Nx.iota(nxn, axis: 1))
 
-    parity = Nx.sum(Nx.dot(p, iota) != iota)
+    parity =
+      Nx.broadcast(transitions, nxn, axes: [0])
```
Comment (polvalente) [inline nx/lib/nx/lin_alg.ex:1208]:
```suggestion
      transitions
      |> Nx.broadcast(nxn, axes: [0])
```

**Review by polvalente — APPROVED** [review]
