### PR TITLE
Ensure SVD works with f16/bf16, closes #1177

### LINKED ISSUE #1177: SVD does not support :f16 and :bf16 types
The following code generates error:

```elixir
x = Nx.tensor([[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4]], type: :f16)
Nx.LinAlg.svd(x)
```

```
** (CompileError) /home/mateusz/.cache/mix/installs/elixir-1.14.2-erts-13.1.4/4d1435fa13ffc3d4da040c8406b8311c/deps/nx/lib/nx/lin_alg/svd.ex:170: the do-block in while must return tensors with the same shape, type, and names as the initial arguments.

Body matches template:

{#Nx.Tensor<
   f32[4][4]
 >, #Nx.Tensor<
   f32
 >, #Nx.Tensor<
   s64
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   s64
 >}

and initial argument has template:

{#Nx.Tensor<
   f16[4][4]
 >, #Nx.Tensor<
   f32
 >, #Nx.Tensor<
   s64
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   s64
 >}

    (nx 0.5.2) lib/nx/defn/expr.ex:483: Nx.Defn.Expr.compatible_while!/4
    (nx 0.5.2) lib/nx/defn/expr.ex:354: Nx.Defn.Expr.defn_while/6
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:170: Nx.LinAlg.SVD."__defn:qdwh__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:140: Nx.LinAlg.SVD."__defn:svd_tall_and_square__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:76: Nx.LinAlg.SVD."__defn:svd_full__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:1: Nx.LinAlg.SVD."__defn:svd_non_zero__"/2
    (nx 0.5.2) lib/nx/defn/expr.ex:300: anonymous fn/4 in Nx.Defn.Expr.defn_cond/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

File: nx/lib/nx/lin_alg/svd.ex [hunk 1]
```diff
@@ -200,12 +202,17 @@ defmodule Nx.LinAlg.SVD do
...
 
+    u = Nx.as_type(u, original_type)
     u = 1.5 * u - 0.5 * Nx.dot(u, Nx.dot(Nx.LinAlg.adjoint(u), u))
     h = u |> Nx.LinAlg.adjoint() |> Nx.dot(x)
     h = (h + Nx.LinAlg.adjoint(h)) / 2
     {u, h}
   end
 
+  # f16 is not enough precision to compute SVD
+  deftransformp min_precision_type({:f, 64}), do: {:f, 64}
```
Comment (polvalente) [inline nx/lib/nx/lin_alg/svd.ex:213]: IIRC the code only works for f32 (even Jax enforces this), but I might be wrong.

**Review by polvalente — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
