### PR TITLE
fix: support wide matrices for backends other than the binary backend

### LINKED ISSUE #444: EXLA SVD dimensions mismatch when first dimension larger than second
Doing an SVD through the EXLA backend, like so:
```elixir
defmodule MyModule do
  import Nx.Defn
  @defn_compiler EXLA
  defn svd(m, opts \\ []) do
    Nx.LinAlg.svd(m, opts)
  end
end

exla_tensor = signal_tensor  |> Nx.backend_transfer(EXLA.DeviceBackend)
{u, s, v} = MyModule.svd(exla_tensor, eps: 1.0e-9)
```

generates the following error when the first dimension is smaller than the second (in this case for a `1023x1431` matrix):
```
** (RuntimeError) internal bug! Nx.Defn expected a tensor with shape {1431} but got {1023}
    (exla 0.1.0-dev) lib/exla/defn.ex:1085: EXLA.Defn.each_buffer_to_nx/2
    (elixir 1.12.1) lib/enum.ex:1675: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.12.1) lib/enum.ex:1675: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (exla 0.1.0-dev) lib/exla/defn.ex:1061: EXLA.Defn.each_buffer_to_nx/2
    (exla 0.1.0-dev) lib/exla/defn.ex:1056: EXLA.Defn.buffer_to_nx/2
```

Transposing the matrix makes the error go away, and it is generated at the end of the calculations, presumably when the output buffers are being asssembled.

I believe this was with master at https://github.com/elixir-nx/nx/commit/65c05bd2cef5317316348f200e3dfa5f7a18d56b

### PR DESCRIPTION
**Pull request by polvalente**
Fixes the Nx.Shape rule for SVD, allowing for all kinds of matrices.
Some backends, like BinaryBackend, may raise depending on the implementation
limitations.

closes #444

### CODE REVIEW

File: nx/lib/nx/binary_backend/matrix.ex [hunk 1]
```diff
@@ -358,11 +364,18 @@ defmodule Nx.BinaryBackend.Matrix do
       |> Enum.map(fn {row, idx} -> Enum.at(row, idx) end)
       |> Enum.reject(&is_nil/1)
 
-    {s, v} = apply_singular_value_corrections(s, v)
+    {s, [vt_row | _] = vt} = apply_singular_value_corrections(s, vt)
+
+    # TO-DO: complete the vtt matrix with linearly independent rows
```
Comment (polvalente) [inline nx/lib/nx/binary_backend/matrix.ex:369]:
```suggestion
    # TO-DO: complete the vt matrix with linearly independent rows
```

File: nx/lib/nx/binary_backend/matrix.ex [hunk 2]
```diff
@@ -358,11 +364,18 @@ defmodule Nx.BinaryBackend.Matrix do
...
+    # requires solvting a homogeneous equation system for non-homogenous
```
Comment (polvalente) [inline nx/lib/nx/binary_backend/matrix.ex:370]:
```suggestion
    # requires solving a homogeneous equation system for non-homogenous
```

File: nx/lib/nx/shape.ex [hunk 3]
```diff
@@ -1435,8 +1435,8 @@ defmodule Nx.Shape do
         "tensor must have rank 2, got rank #{tuple_size(shape)} with shape #{inspect(shape)}"
       )
 
-  def svd({m, n}) do
-    {{m, m}, {n}, {n, n}}
+  def svd({m, n}) when m >= n do
```
Comment (polvalente) [inline nx/lib/nx/shape.ex:1438]:
```suggestion
  def svd({m, n}) do
```

File: nx/lib/nx/binary_backend.ex [hunk 4]
```diff
@@ -1172,12 +1172,16 @@ defmodule Nx.BinaryBackend do
 
   @impl true
   def svd(
-        {u_holder, %{type: output_type} = s_holder, v_holder},
+        {%{shape: {m, _}} = u_holder, s_holder, %{shape: {_, n}} = v_holder} = outputs,
         %{type: input_type, shape: input_shape} = tensor,
         opts
       ) do
+    if m < n do
+      raise ArgumentError, "SVD not implemented for wide matrices (m x n 2-D tensors where m < n)"
```
Comment (seanmor5) [inline nx/lib/nx/binary_backend.ex:1180]: Just a nit: the `m x n` is kind of difficult to read, maybe:

```suggestion
      raise ArgumentError, "SVD not implemented for wide matrices (tensors with shape {m, n} where m < n)"
```

**Review by seanmor5 — APPROVED** [review]
Nice work :)

File: nx/lib/nx/binary_backend.ex (hunk 4 above)
Comment (polvalente) [reply nx/lib/nx/binary_backend.ex:1180]: Thanks! Brainfart, because this is how all of the other exceptions talk about shapes lol
