### PR TITLE
fix: vectorized cond with numeric literal leaf

### LINKED ISSUE #1381: Issue with using vectorized tensor in a function
I have the following code:

```elixir
data = Nx.vectorize(data, :x)
knn = query_one_point(data, tree, opts)
```

where `query_one_point` is a function that previously took one element of the data [see here](https://github.com/elixir-nx/scholar/blob/8826219bfa978aaf360971b4a4efb6dd6ac19b68/lib/scholar/neighbors/kd_tree.ex#L465). Currently the second line returns the following error:

```
** (KeyError) key :vectorized_axes not found in: 1
     
     If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
     stacktrace:
       (nx 0.6.4) lib/nx/defn/expr.ex:166: anonymous fn/1 in Nx.Defn.Expr.cond/2
       (nx 0.6.4) lib/nx/defn/composite.ex:104: anonymous fn/3 in Nx.Defn.Composite.traverse/2
       (elixir 1.15.5) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.15.5) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (nx 0.6.4) lib/nx/container.ex:113: Nx.Container.Tuple.traverse/3
       (nx 0.6.4) lib/nx/defn/composite.ex:104: Nx.Defn.Composite.traverse/2
       (nx 0.6.4) lib/nx/defn/expr.ex:165: Nx.Defn.Expr.cond/2
       (nx 0.6.4) lib/nx/defn/expr.ex:435: anonymous fn/4 in Nx.Defn.Expr.defn_cond/2
       (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       (nx 0.6.4) lib/nx/defn/expr.ex:433: Nx.Defn.Expr.defn_cond/2
       (nx 0.6.4) lib/nx/defn/expr.ex:435: anonymous fn/4 in Nx.Defn.Expr.defn_cond/2
       (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       (nx 0.6.4) lib/nx/defn/expr.ex:433: Nx.Defn.Expr.defn_cond/2
       (scholar 0.2.1) lib/scholar/neighbors/kd_tree.ex:1: anonymous fn/6 in Scholar.Neighbors.KDTree."__defn:query_one_point__"/3
       (nx 0.6.4) lib/nx/defn/expr.ex:517: Nx.Defn.Expr.while_vectorized/7
       (scholar 0.2.1) lib/scholar/neighbors/kd_tree.ex:485: Scholar.Neighbors.KDTree."__defn:query_one_point__"/3
       (nx 0.6.4) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
       (nx 0.6.4) lib/nx/defn/evaluator.ex:83: Nx.Defn.Evaluator.precompile/3
       (nx 0.6.4) lib/nx/defn/evaluator.ex:61: Nx.Defn.Evaluator.__compile__/4
       (nx 0.6.4) lib/nx/defn/evaluator.ex:54: Nx.Defn.Evaluator.__jit__/5
```

### PR DESCRIPTION
**Pull request by polvalente**
closes #1381

### CODE REVIEW

File: nx/lib/nx/defn/expr.ex [hunk 1]
```diff
@@ -163,7 +163,14 @@ defmodule Nx.Defn.Expr do
 
       zero =
         Composite.traverse(last, fn leaf ->
-          Nx.broadcast(0, Nx.devectorize(leaf).shape) |> Nx.vectorize(leaf.vectorized_axes)
+          vectorized_axes =
+            case leaf do
+              %{vectorized_axes: vectorized_axes} -> vectorized_axes
+              number when is_number(number) -> []
```
Comment (josevalim) [inline nx/lib/nx/defn/expr.ex:169]: I guess this could be anything, including a complex, so at best we should use is_tensor. But perhaps the best is to call `to_tensor(left)` before?

Comment (polvalente) [reply nx/lib/nx/defn/expr.ex:169]: You know, I thought about complex when writing this and forgot to test and add the case haha

Comment (polvalente) [reply nx/lib/nx/defn/expr.ex:169]: to_tensor(left) is the more uniform and easier solution

**Review by josevalim — APPROVED** [review]
